In [44]:
import numpy as np

name = ['Alice', 'Bob', 'Max']
age = [25, 45, 37, 19]
weight = [55.0, 85.0, 68.0, 61.5]

In [37]:
x = np.zeros(4, dtype=int)

In [38]:
data = np.zeros(4,dtype={'names':('name','age','weigth'),
                        'formats':('U10','i4','f8')})
print(data.dtype)

[('name', '<U10'), ('age', '<i4'), ('weigth', '<f8')]


In [46]:
data['name']= name
data['age']= age
data['weight']= weight
print(data)

[('Alice', 25, 55. ) ('Bob', 45, 85. ) ('Max', 37, 68. )
 ('John', 19, 61.5)]


In [47]:
data['name']

array(['Alice', 'Bob', 'Max', 'John'], dtype='<U10')

In [48]:
data['age']

array([25, 45, 37, 19], dtype=int32)

In [49]:
data['weight']

array([55. , 85. , 68. , 61.5])

In [50]:
data[1]

('Bob', 45, 85.)

In [51]:
data[-1]['name']

'John'

In [54]:
import numpy as np

# Updated name list to have 4 elements to match age and weight
name = ['Alice', 'Bob', 'Max', 'John']
age = [25, 45, 37, 19]
weight = [55.0, 85.0, 68.0, 61.5]

# Creating a structured array
data = np.zeros(4, dtype={'names': ('name', 'age', 'weight'),
                          'formats': ('U10', 'i4', 'f8')})

# Assigning values
data['name'] = name
data['age'] = age
data['weight'] = weight

# Output the structured array and its dtype
print(data.dtype)
print(data)

[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')]
[('Alice', 25, 55. ) ('Bob', 45, 85. ) ('Max', 37, 68. )
 ('John', 19, 61.5)]


In [53]:
data[data['age']>30]['name']

array(['Bob', 'Max'], dtype='<U10')

In [ ]:
##СОЗДАНИЕ СТРУКТУРИРОВАННЫХ МАССИВОВ

In [55]:
np.dtype({'names': ('name','age','weight'),
         'formats':('U10','i4','f8')})

dtype([('name', '<U10'), ('age', '<i4'), ('weight', '<f8')])

In [58]:
np.dtype({'names': ('name','age','weight'),
         'formats':((np.str_,10), int, np.float32)})

dtype([('name', '<U10'), ('age', '<i8'), ('weight', '<f4')])

In [62]:
np.dtype([('name', 'S10'), ('age', 'i4'), ('weight', 'f8')])


dtype([('name', 'S10'), ('age', '<i4'), ('weight', '<f8')])

In [63]:
np.dtype('S10,i4,f8')

dtype([('f0', 'S10'), ('f1', '<i4'), ('f2', '<f8')])

In [66]:
tp = np.dtype([('id','i8'),('mat','f8',(3,3))])
x = np.zeros(1,dtype = tp)
print(x[0])
print(x['mat'][0])

(0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [70]:
data['age']

array([25, 45, 37, 19], dtype=int32)

In [71]:
data_rec = data.view(np.recarray)
data_rec.age

array([25, 45, 37, 19], dtype=int32)

In [75]:
%timeit data['age']
%timeit data_rec['age']
%timeit data_rec.age

52.4 ns ± 0.335 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)
705 ns ± 3.35 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
1.35 µs ± 4.5 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
