In [1]:
L = list(range(10))

In [2]:
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
type(L[0])

int

In [10]:
L2 = [str(w) for w in L]

In [11]:
type(L2[0])

str

In [12]:
L2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [15]:
L3 = [ True, "2" , 3.0, 4]
[type(item) for item in L3]

[bool, str, float, int]

In [19]:
import array
L = list (range(10))
A = array.array('i', L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
import numpy as np

In [25]:
np.array([3.12, 4, 2, 3])

array([3.12, 4.  , 2.  , 3.  ])

In [33]:
 np.array([range(i,i+3) for i in [3,6,9]])


array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [36]:
reversed_arr = arr[::-1, ::-1]
reversed_arr

array([[11, 10,  9],
       [ 8,  7,  6],
       [ 5,  4,  3]])

In [48]:
np.zeros(10, dtype =int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [41]:
np.ones((3, 5) , dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [42]:
np.full((3,5) , 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [51]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [52]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [53]:
np.random.random((3,3))

array([[0.54600416, 0.5813724 , 0.5377283 ],
       [0.93502864, 0.59831004, 0.7002767 ],
       [0.69575689, 0.55091901, 0.70133114]])

In [59]:
np.random.normal(0,10,(3,3))

array([[  0.31220444, -26.1747241 , -24.05122075],
       [ -1.58715189,  12.89643322,   0.69968093],
       [ -3.92987726,  -7.29430141,  -1.84829325]])

In [60]:
np.random.randint(0,10,(3,3))

array([[5, 2, 6],
       [4, 9, 4],
       [9, 9, 0]])

In [61]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [65]:
np.empty(3)

array([1., 1., 1.])

In [66]:
np.zeros(10, dtype = 'int16')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [67]:
np.zeros(10, dtype = np.int16)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)