In [2]:
## Chapter ## 9

In [5]:
import numpy as np


In [6]:
rng = np.random.default_rng(seed=1701)
x = rng.integers(10, size=(3,4))
x

array([[9, 4, 0, 3],
       [8, 6, 3, 1],
       [3, 7, 4, 0]])

In [7]:
x < 6

array([[False,  True,  True,  True],
       [False, False,  True,  True],
       [ True, False,  True,  True]])

In [8]:
np.count_nonzero(x<6)

8

In [10]:
np.sum(x<6)

8

In [11]:
np.sum(x<6,axis=1)

array([3, 2, 3])

In [12]:
np.any(x<8)

True

In [13]:
np.any(x<0)

False

In [19]:
np.all(x<10)

True

In [20]:
np.all(x==6)

False

In [21]:
np.all(x<8, axis =1 )

array([False, False,  True])

In [49]:
rainfall_mm = 1

np.sum((rainfall_mm>10)&(rainfall_mm<20))

0

In [50]:
rainfall_mm > (10&rainfall_mm) < 20

True

In [51]:
np.sum(~( (rainfall_mm<=10)|(rainfall_mm>=20) ))

/var/folders/w_/x158hy914jv595q6kdm333n80000gn/T/ipykernel_66260/3764210150.py:1: DeprecationWarning: Bitwise inversion '~' on bool is deprecated. This returns the bitwise inversion of the underlying int object and is usually not what you expect from negating a bool. Use the 'not' operator for boolean negation or ~int(x) if you really want the bitwise inversion of the underlying int.
  np.sum(~( (rainfall_mm<=10)|(rainfall_mm>=20) ))


-2

In [52]:
np.sum(np.logical_not((rainfall_mm <= 10) | (rainfall_mm >= 20)))

0

In [53]:
x

array([[9, 4, 0, 3],
       [8, 6, 3, 1],
       [3, 7, 4, 0]])

In [54]:
x<5

array([[False,  True,  True,  True],
       [False, False,  True,  True],
       [ True, False,  True,  True]])

In [55]:
x[x<5]

array([4, 0, 3, 3, 1, 3, 4, 0])

In [83]:
rainy = (rainfall_mm >0 )
days=np.arange(365)
summer=(days>172)&(days<262)

In [88]:

print("Median on rainy for 2015 (mm): ", np.median(rainfall_mm[rainy]))

print("Median on summer for 2015 (mm): ", np.median(rainfall_mm[summer]))

print("Maximum on summer for 2015 (mm): ", np.max(rainfall_mm[summer]))

print("Median rainfall for 2015 (mm): ", np.median(rainfall_mm[rainy & ~summer]))

Median on rainy for 2015 (mm):  24.689460814358625
Median on summer for 2015 (mm):  26.17779929720008
Maximum on summer for 2015 (mm):  49.87423936707667
Median rainfall for 2015 (mm):  24.27143383281885


In [90]:
bool(42), bool(0)

(True, False)

In [91]:
bool(42 and 0)

False

In [92]:
bool(42 or 0)

True

In [93]:
bin(42)

'0b101010'

In [94]:
bin(59)

'0b111011'

In [95]:
bin(42&59)

'0b101010'

In [96]:
bin(42|59)

'0b111011'

In [102]:
A = np.array([1,0,1,1,0], dtype=bool)
B = np.array([1,1,1,1,0], dtype=bool)

A|B

array([ True,  True,  True,  True, False])

In [109]:
x = np.arange(18)
(x>4)&(x<8)

array([False, False, False, False, False,  True,  True,  True, False,
       False, False, False, False, False, False, False, False, False])

In [112]:
In[40]: (x>4)&(x<8)